### ISSUE TITLE
Review from Wei

### ISSUE THREAD

**Issue by zhengweifz** [gwsb-istm-6212-fall-2016/KBFitz#2]
Hi Kevin,

Good Job!  I was able to run all cells with only intentional errors, which you use to demonstrate your thought process. And I appreciate that you clearly describe your thought process for each step. Your queries answer your research questions well.  The below are some of my suggestions:
1. You may want to add foreign-key constraints for dimensional keys in the fact table.
2. Null values may be better to be mapped to "unknown" or "invalid" to provide more meaningful answers.
3. A date dimension may be helpful to examine seasonal impacts of donations.
Once again, great job!

Wei

**Comment by KBFitzgerald** [comment]
Thanks Wei. Your suggestions are right on target and I appreciate that. Cheers! - Kevin
